In [38]:
import sys
print(sys.version)

3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]

In [39]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [40]:
FILE_PATH = '/content/drive/MyDrive/Carisurg_Triage_Test/EmergencyTriageDataset_Reduced_Dirty.csv'

df_raw = pd.read_csv(FILE_PATH)

In [41]:
df_raw['Gender'].unique()

array(['0', 'Male', 'Female', 'FEMALE', '1', 'MALE'], dtype=object)

In [42]:
df_raw['Gender'].value_counts()

Gender
1         422
MALE      379
Male      375
FEMALE    366
Female    340
0         323
Name: count, dtype: int64

In [43]:
gender_mapping = {
    '1': 1, 'Male': 1, 'MALE': 1,
    '0': 0, 'Female': 0, 'FEMALE': 0
}

In [44]:
df_raw['Gender'] = df_raw['Gender'].map(gender_mapping)

In [45]:
df_raw['Gender'].value_counts()

Gender
1    1176
0    1029
Name: count, dtype: int64

In [47]:
df_raw = df_raw.rename(columns={'Gender': 'Gender_clean'})
df_raw.head()

   ID  Age  Gender_clean   GCS  SBP    DBP     MAP  pulse  Temp    RR   Fio2
0   1   34             0  15.0   93   67.0   75.67  128.0  36.8  14.0   21.0
1   2   20             1  15.0  130   90.0  103.33   80.0  37.0  16.0   21.0
2   3   77             0  14.0  163  105.0  124.33   92.0  36.8  18.0   21.0
3   4   23             0   8.0  100   60.0   73.33  100.0  37.0  12.0  100.0
4   5   86             0  15.0  150   90.0  110.00   85.0  37.0  19.0   21.0